### ISSUE TITLE
Publish on cocoapods 

### ISSUE THREAD

**Issue by jdegger** [50ButtonsEach/flic2lib-ios#1]
It would be beneficial to the adoptability of this plugin if it was published as a Pod.

https://guides.cocoapods.org/making/making-a-cocoapod.html

For example, the react native plugin we are working on wouldn't have to included in the library and whenever you update your project, it will also be updated in ours.

An example of how we include a twilio plugin:

```
pod 'TwilioVoice', '~> 2.1.0'
pod 'RNTwilioVoice', path: '../node_modules/react-native-twilio-programmable-voice'
```

In our case the first line would be your published Pod and the second line would be our plugin. 

Of course the implementation is beneficial to all iOS projects, they can simply install this SDK with one simple dependency inclusion.

**Comment by AntonMeier** [comment]
Thank you for your input! We will discuss this more internally and get back to you later with a better answer. But I think people have a lot of mixed opinions when it comes to publishing via cocoapods.

**Comment by jdegger** [comment]
We are mostly active in the React Native ecosystem where everything is Cocao based so we might be a bit biased. 

Thanks for considering it!
