### ISSUE TITLE
Missing features compared to Flic 1 API

### ISSUE THREAD

**Issue by PaulKlein** [50ButtonsEach/flic2lib-ios#14]
Hi there,
We are currently using the Fliclib-ios (Flic 1) API, and are looking at integrating Flic 2 as well.

Looking at the new API, there seem to be a few things possible in Flic 1 which aren't available in Flic 2.

Could you please consider adding the following functionality:

 - Ability to disable/enable all bluetooth generally. Fliclib had the `disable` and `enable` functions on the `SCLFlicManager`. Is there any equivalent in flic2lib-ios?
 - Ability to control the LED on the button. Fliclib had the `indicateLED` function on the `SCLFlicButton`

Thanks for any help here, or any equivalent way of accomplishing these.

**Comment by oskob** [comment]
Hi! 

To achieve a similar functionality you can call disconnect on all buttons. The reason we removed this was to reduce unnecessary state handling inside the lib itself.

Removing the ability to access the LED was a design decision based on how much power the LED is consuming and it not being ideal as a means of indicating feedback.
