### ISSUE TITLE
arm64 Simulator (Apple Silicon)

### ISSUE THREAD

**Issue by Maxmad68** [50ButtonsEach/flic2lib-ios#19]
Hi,
The framework is only compiled for x64 and i386 for the iOS Simulator.
The simulator uses the same architecture as the computer it runs on. For the DTK, it is arm64.
Building an app that use the flic2lib framework for the simulator on a DTK fails because the framework is not compiled for this architecture (arm64).
Please re-build your framework on the latest Xcode 12 beta to make sure it is compatible with every cpu architecture.
Have a nice day

**Comment by AntonMeier** [comment]
Sorry for the delay, but release 1.2.0 now supports Apple Silicon simulator, as well as Mac Catalyst.
