### ISSUE TITLE
swift can not work

### ISSUE THREAD

**Issue by biangou** [50ButtonsEach/flic2lib-ios#2]
hello,
I read your code that wirte by Objective-C,and I can write right Objective-C code when It is an Objective-C project.
but It can not work as I expected when I take my code to an swift project ,The  FLICButtondelegate can not run and scan is not useful .

**Comment by AntonMeier** [comment]
We will release Swift code example soon.

**Comment by AnthoPgt** [comment]
> We will release Swift code example soon.

Do you know when ?

Thanks

**Comment by AntonMeier** [comment]
Yes, last week: [https://github.com/50ButtonsEach/flic2lib-ios-sample](https://github.com/50ButtonsEach/flic2lib-ios-sample)
:)
