### ISSUE TITLE
"Embed Without Signing" option causes installation to fail

### ISSUE THREAD

**Issue by marcoburato** [50ButtonsEach/flic2lib-ios#3]
According to the instructions, we're supposed to add the fli2lib.framework and set the options "Embed Without Signing", however if I do that I can't debug the app on my iPhone.

This error window appears:

    Unable to install '<appname>'
    Domain: com.apple.dtdevicekit
    Code: -402620395
    --
    App installation failed
    Domain: com.apple.dtdevicekit
    Code: -402620395
    Failure Reason: A valid provisioning profile for this executable was not found.

When I choose "Embed & Sign", the app transfers correctly and I can debug it.
I've tried many things like restarting the iPhone, rebuilding with legacy build system, etc. Nothing worked. I'm not sure how the embedding works, but it sounds reasonable that it should be signed with my development certificate to run on my device.

**Comment by AntonMeier** [comment]
Yes you are correct, my bad! I don't know what I was thinking when I made the tutorial.

But yes, you need to use the "Embed & Sign" option in order to make it run in your application. I will update the tutorial.

Thank you for letting me know!

**Comment by marcoburato** [comment]
No problem.
BTW, if you're interested I have some feedback regarding the documentation. I'm not sure if I should open another issue or some other channel is more appropriate.

**Comment by AntonMeier** [comment]
Yes, that would be appreciated! The documentation was a bit rushed so we will be looking to improve it going forward. Feedback is definitely welcome.

I think it would be easiest to follow up on it if you put all the feedback in one Github Issue.
