### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by marhas** [50ButtonsEach/flic2lib-ios#31]
Hi,
I just added the flic2lib framework to my app and when uploading it to the App Store I received the following error:

```
ITMS-90863: Macs with Apple silicon support issue - The app links with libraries that aren’t present in macOS:

@rpath/flic2lib.framework/flic2lib
```

My app is an iOS app but marked as being available also on Silicon Macs. I believe this is also the default setting for new apps.
I think that recompiling the framework on the latest version of Xcode with standard architectures will solve the issue. 

Thanks,
Marcel

**Comment by oskob** [comment]
Hi!

Could you try this branch and see if this works?
https://github.com/50ButtonsEach/flic2lib-ios/tree/1.3.0

**Comment by marhas** [comment]
It works very well, thank you!
TBH my issue seems to be resolved by including flic2lib as a package dependency. I previously included it "old style" by dragging the xcframework into my project and I think the embed setting was wrong.
I think the error message from AppStore Connect was pretty misleading indicating it was an Apple Silicon issue.
