### ISSUE TITLE
[Question] PbF SDK?

### ISSUE THREAD

**Issue by backslash-f** [50ButtonsEach/flic2lib-ios#6]
Hi, would we need the `PbF SDK` to support Flic 2 buttons?
https://flic.io/business/solutions

Or does the `PbF SDK` apply to Flic 1 only?

Reason I ask is (snippet from the above link): _"This option is best if you are looking to white label our PbF buttons with your branding `and connect them exclusively with your own application`."_

But based on the documentation of Flic 2, it seems that we can _"`connect them exclusively with your own application`"_ using the `flic2lib-ios` SDK.

Please advise. Thanks!

**Comment by AntonMeier** [comment]
The concept of 'PbF' only applies to the original Flic. With Flic 2 there is only one SDK. We have yet to update the information on our website about it. But all Flic 2's can be connected directly to your application whether they are white label or not.

**Comment by backslash-f** [comment]
Thank you.
